### ISSUE TITLE
process.getuid is not a function on windows 

### ISSUE THREAD

**Issue by lordunited** [mimshins/figma-backup#3]
C:\Users\admin\AppData\Roaming\npm\node_modules\figma-backup\lib\Bot.js:149
        const isRootUser = process.getuid() === 0;
                                   ^

TypeError: process.getuid is not a function
    at Bot.start (C:\Users\admin\AppData\Roaming\npm\node_modules\figma-backup\lib\Bot.js:149:36)
    at startBot (C:\Users\admin\AppData\Roaming\npm\node_modules\figma-backup\lib\index.interactive.js:100:8)
    at run (C:\Users\admin\AppData\Roaming\npm\node_modules\figma-backup\lib\index.interactive.js:104:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

using this commands 
npm install -g figma-backup
npm update -g figma-backup
trying with yarn also.
node modules folder also created . 
any idea??

**Comment by mimshins** [comment]
@MohammadrezaMasoumi 
This issue should be fixed now.
Try to get the latest version of the package. (Update to the latest version: `npm update -g figma-backup`)

**Comment by lordunited** [comment]
thanks
